### ISSUE TITLE
Config or yaml error...

### ISSUE THREAD

**Issue by ghost** [zyrouge/xeno-bot-list#5]
```/rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/index.js:57
  if (doc.errors.length > 0) throw doc.errors[0];
                             ^
YAMLSyntaxError: All collection items must start at the same column
    at Collection.parse (/rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:331:24)
    at /rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:1605:29
    at CollectionItem.parse (/rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:92:19)
    at /rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:1586:25
    at Collection.parse (/rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:350:20)
    at /rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:1605:29
    at Document.parseContents (/rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:622:26)
    at Document.parse (/rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:685:19)
    at Object.parse (/rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/parse-cst.js:1723:18)
    at parseDocument (/rbd/pnpm-volume/b93abef7-8a49-446d-97f2-db40675aad7a/node_modules/.registry.npmjs.org/yaml/1.10.0/node_modules/yaml/dist/index.js:43:24)```
Idk what is causing this error...
@zyrouge [My glitch site editing](https://glitch.com/edit/#!/join/00fec75e-9ecc-49c0-8e6a-fb96c041e235) pls help me

**Comment by ghost** [comment]
Sorry, but my mistake is solved...
